jobs:
  - name: generate-manifest-2
    type: manifest
    steps:
      - GET nginx-image-2

  - name: deploy-service-2
    type: ecsDeploy
    steps:
      - GET generate-manifest-2
      - GET myEcsCluster-2
